steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_GEMINI_API_KEY=AIzaSyDWqHbhdYASSCtFFDlGFjL6f3lHn8K_vy0'
      - '-t'
      - 'us-central1-docker.pkg.dev/dprintables-ai/dprintables-repo/3dprintables-ai'
      - '.'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/dprintables-ai/dprintables-repo/3dprintables-ai'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'dprintables-ai'
      - '--image'
      - 'us-central1-docker.pkg.dev/dprintables-ai/dprintables-repo/3dprintables-ai'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'

images:
  - 'us-central1-docker.pkg.dev/dprintables-ai/dprintables-repo/3dprintables-ai'
options:
  logging: CLOUD_LOGGING_ONLY
