steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_GEMINI_API_KEY=AIzaSyDWqHbhdYASSCtFFDlGFjL6f3lHn8K_vy0'
      - '-t'
      - 'us-central1-docker.pkg.dev/dprintables-ai/dprintables-repo/3dprintables-ai'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/dprintables-ai/dprintables-repo/3dprintables-ai'
options:
  logging: CLOUD_LOGGING_ONLY
