import React, { useState, useEffect } from 'react';
import { Wand2, Plus, FileSpreadsheet, Package, ArrowLeft, MessageCircle } from 'lucide-react';
import { calculateToyPrice } from '../utils/pricing';
import ProductForm from '../components/admin/ProductForm';
import BulkImport from '../components/admin/BulkImport';
import OrderList from '../components/admin/OrderList';
import InventoryTable from '../components/admin/InventoryTable';
import DeleteConfirmModal from '../components/admin/DeleteConfirmModal';
import MessageCenter from '../components/admin/MessageCenter';

const AdminDashboard = ({ addNewProduct, addBulkProducts, deleteProduct, products, setView, token }) => {
    const [formData, setFormData] = useState({
        name: '',
        weight: '',
        time: '',
        description: '',
        category: '',
        image: null
    });

    const [calculatedPrice, setCalculatedPrice] = useState(null);
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedImage, setGeneratedImage] = useState(null);
    const [activeTab, setActiveTab] = useState('add'); // 'add', 'manage', or 'bulk'
    const [bulkFile, setBulkFile] = useState(null);
    const [isUploading, setIsUploading] = useState(false);
    const [aiProgress, setAiProgress] = useState(null); // null, or 0-100
    const [itemToDelete, setItemToDelete] = useState(null);
    const [orders, setOrders] = useState([]);
    const [isLoadingOrders, setIsLoadingOrders] = useState(false);

    useEffect(() => {
        if (activeTab === 'orders') {
            fetchOrders();
        }
    }, [activeTab]);

    const fetchOrders = async () => {
        setIsLoadingOrders(true);
        try {
            const response = await fetch('/api/orders', {
                headers: { 'Authorization': `Bearer ${token}` }
            });
            const data = await response.json();
            setOrders(data);
        } catch (error) {
            console.error('Failed to fetch orders:', error);
        } finally {
            setIsLoadingOrders(false);
        }
    };

    // Recalculate price when weight/time changes
    useEffect(() => {
        if (formData.weight && formData.time) {
            const result = calculateToyPrice(Number(formData.weight), Number(formData.time));
            setCalculatedPrice(result);
        }
    }, [formData.weight, formData.time]);

    const handleInputChange = (e) => {
        const { name, value, files } = e.target;
        if (name === 'image') {
            const file = files[0];
            if (file) {
                setFormData(prev => ({ ...prev, image: file }));
                const reader = new FileReader();
                reader.onloadend = () => {
                    setGeneratedImage(reader.result); // Show preview immediately
                };
                reader.readAsDataURL(file);
            }
        } else {
            setFormData(prev => ({ ...prev, [name]: value }));
        }
    };

    const generateAIContent = () => {
        if (!formData.image) return;

        setIsGenerating(true);

        // Simulate AI Latency
        setTimeout(() => {
            // Mock AI Response based on "screenshot"
            const adjectives = ["Epic", "Cosmic", "Mystic", "Hyper", "Turbo", "Quantum"];
            const nouns = ["Dragon", "Robot", "Glider", "Artifact", "Gizmo", "Crawler"];
            const randomName = `${adjectives[Math.floor(Math.random() * adjectives.length)]} ${nouns[Math.floor(Math.random() * nouns.length)]}`;

            const cats = ["Action", "Flying", "Puzzle", "Creative", "Water"];

            setFormData(prev => ({
                ...prev,
                name: randomName,
                category: cats[Math.floor(Math.random() * cats.length)],
                description: `Generated by Gemini 3.0 Flash: A cutting-edge 3D printed marvel. This ${randomName.toLowerCase()} features intricate geometry optimized for durability and style. Perfect for collectors and kids alike!`,
            }));

            // Simulate "Nano Banana" image processing (just apply a filter for effect)
            // In a real app, this would be the URL from the image gen API
            setGeneratedImage(current => current);

            setIsGenerating(false);
        }, 2500);
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (!calculatedPrice || !formData.name) return;

        const newProduct = {
            name: formData.name,
            price: calculatedPrice.finalPrice,
            category: formData.category || 'Custom',
            image: generatedImage || "https://placehold.co/400x400/purple/white?text=New+Toy",
            description: formData.description,
            image_prompt: "" // Placeholder if needed
        };

        try {
            const response = await fetch('/api/products', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
                body: JSON.stringify(newProduct)
            });
            const savedProduct = await response.json();

            addNewProduct(savedProduct);
            setActiveTab('manage');
            setFormData({ name: '', weight: '', time: '', description: '', category: '', image: null });
            setGeneratedImage(null);
            setCalculatedPrice(null);
        } catch (error) {
            console.error('Failed to save product:', error);
            alert('Error saving product to database.');
        }
    };

    const handleCSVUpload = (e) => {
        const file = e.target.files[0];
        if (file) {
            setBulkFile(file);
        }
    };

    const processCSV = () => {
        if (!bulkFile) return;
        setIsUploading(true);
        setAiProgress(0);

        const reader = new FileReader();
        reader.onload = async (e) => {
            try {
                const text = e.target.result;
                const rows = text.split('\n').filter(row => row.trim() !== '');

                // Skip header if it exists
                const startIdx = rows[0].toLowerCase().includes('name') ? 1 : 0;
                const rawData = rows.slice(startIdx);
                const enhancedProducts = [];

                for (let i = 0; i < rawData.length; i++) {
                    const row = rawData[i];
                    const [rawName, price, category, image, rawDesc] = row.split(',').map(item => item.trim());

                    // --- Gemini AI Simulation Engine ---
                    const prefixes = ["Ultra", "Hyper", "Neo", "Quantum", "Apex", "Zenith", "Aero", "Magno"];
                    const suffixes = ["Pro", "Prime", "Elite", "Core", "Vance", "Sphere", "Shift", "Grid"];

                    // Enhance Name
                    let finalName = rawName || "Mystery Toy";
                    if (finalName.length < 5 || Math.random() > 0.7) {
                        const prefix = prefixes[Math.floor(Math.random() * prefixes.length)];
                        const suffix = suffixes[Math.floor(Math.random() * suffixes.length)];
                        finalName = `${prefix} ${finalName} ${suffix}`;
                    }

                    const finalCategory = category || "Limited Edition";

                    // Generate Description Template
                    const templates = [
                        `Gemini AI Analysis: This ${finalName} represents the peak of ${finalCategory} design. Features include optimized 3D geometry for structural resilience and a premium aerodynamic silhouette.`,
                        `Powered by Gemini Flash: A deep dive into ${finalCategory} aesthetics. The ${finalName} utilizes variable infill patterns for a perfect balance of weight and durability.`,
                        `Gemini Optimized: Designed for explorers. This ${finalName} in our ${finalCategory} line features precision joints and a unique texture generated using generative noise algorithms.`,
                        `Gemini Pro Insight: Elegance meets engineering. The ${finalName} is a standout piece in the ${finalCategory} category, boasting high-detail surfaces and a play-tested balance.`
                    ];

                    const geminiDescription = rawDesc && rawDesc.length > 50
                        ? rawDesc
                        : templates[Math.floor(Math.random() * templates.length)];

                    enhancedProducts.push({
                        id: `bulk-${Date.now()}-${i}-${Math.random().toString(36).substr(2, 9)}`,
                        name: finalName,
                        price: parseFloat(price) || (15 + Math.random() * 40).toFixed(2),
                        category: finalCategory,
                        image: image || `https://placehold.co/400x400/purple/white?text=${finalName.replace(/ /g, '+')}`,
                        description: geminiDescription,
                        rating: (4 + Math.random()).toFixed(1)
                    });

                    // Update progress
                    setAiProgress(Math.round(((i + 1) / rawData.length) * 100));

                    // Simulation delay for "AI Thinking"
                    await new Promise(resolve => setTimeout(resolve, 350));
                }

                addBulkProducts(enhancedProducts);
                setBulkFile(null);
                setAiProgress(null);
                setActiveTab('manage');
            } catch (error) {
                console.error("CSV Parse Error:", error);
                alert("Error parsing CSV. Please check the format.");
                setAiProgress(null);
            } finally {
                setIsUploading(false);
            }
        };
        reader.readAsText(bulkFile);
    };

    return (
        <div className="container mx-auto px-4 py-12">
            <div className="max-w-6xl mx-auto">
                {/* Header & Tabs */}
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-12">
                    <div className="flex items-center gap-6">
                        <button onClick={() => setView('home')} className="p-3 bg-white/5 hover:bg-white/10 rounded-2xl text-purple-400 transition-all border border-white/5">
                            <ArrowLeft />
                        </button>
                        <div>
                            <h2 className="text-4xl font-black text-white tracking-tighter uppercase">Admin <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-500">Dashboard</span></h2>
                            <p className="text-gray-500 text-xs font-black uppercase tracking-[0.3em] mt-1 italic">Manage Products & Orders</p>
                        </div>
                    </div>

                    <div className="flex bg-gray-950/80 backdrop-blur-xl p-1.5 rounded-[2rem] border border-white/5 overflow-x-auto shadow-2xl">
                        {[
                            { id: 'add', label: 'Add Product', icon: <Plus size={16} /> },
                            { id: 'bulk', label: 'Bulk Import', icon: <FileSpreadsheet size={16} /> },
                            { id: 'orders', label: 'Orders', icon: <Package size={16} /> },
                            { id: 'messages', label: 'Messages', icon: <MessageCircle size={16} /> },
                            { id: 'manage', label: `Inventory (${products.length})`, icon: <Wand2 size={16} /> }
                        ].map(tab => (
                            <button
                                key={tab.id}
                                onClick={() => setActiveTab(tab.id)}
                                className={`px-6 py-3 rounded-2xl font-black transition-all whitespace-nowrap flex items-center gap-2 text-xs uppercase tracking-widest ${activeTab === tab.id ? 'bg-purple-600 text-white shadow-[0_0_20px_rgba(168,85,247,0.3)]' : 'text-gray-500 hover:text-gray-300'}`}
                            >
                                {tab.icon} {tab.label}
                            </button>
                        ))}
                    </div>
                </div>

                {/* Main Content Sections */}
                {activeTab === 'add' && (
                    <ProductForm
                        formData={formData}
                        handleInputChange={handleInputChange}
                        generateAIContent={generateAIContent}
                        isGenerating={isGenerating}
                        handleSubmit={handleSubmit}
                        generatedImage={generatedImage}
                        calculatedPrice={calculatedPrice}
                    />
                )}

                {activeTab === 'bulk' && (
                    <BulkImport
                        bulkFile={bulkFile}
                        handleCSVUpload={handleCSVUpload}
                        processCSV={processCSV}
                        isUploading={isUploading}
                        aiProgress={aiProgress}
                        setActiveTab={setActiveTab}
                    />
                )}

                {activeTab === 'orders' && (
                    <OrderList orders={orders} isLoadingOrders={isLoadingOrders} token={token} />
                )}

                {activeTab === 'messages' && (
                    <MessageCenter token={token} />
                )}

                {activeTab === 'manage' && (
                    <InventoryTable products={products} setItemToDelete={setItemToDelete} />
                )}

                {/* Modals */}
                <DeleteConfirmModal
                    itemToDelete={itemToDelete}
                    setItemToDelete={setItemToDelete}
                    deleteProduct={deleteProduct}
                />
            </div>
        </div>
    );
};

export default AdminDashboard;
